version: "3.9"
services:
  db:
    image: mysql:8.0.33
    platform: linux/amd64 # mac m1
    restart: always
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: local
      MYSQL_USER: local
      MYSQL_PASSWORD: password
      TZ: Asia/Seoul
